// <auto-generated />
using System;
using Infra.Configuracao;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USR_CPF");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Bairro", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("MunicipioId");

                    b.ToTable("Bairro", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdSistema")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("Entities.Models.CodigoBarra", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Altura")
                        .HasColumnType("numeric(10, 3)");

                    b.Property<string>("CodigoBarras")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("Comprimento")
                        .HasColumnType("numeric(10, 0)");

                    b.Property<decimal?>("Largura")
                        .HasColumnType("numeric(10, 3)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CodigoBarras" }, "UC_CodigoBarra")
                        .IsUnique();

                    b.ToTable("CodigoBarra", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Despesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DespesaAntrasada")
                        .HasColumnType("bit");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Pago")
                        .HasColumnType("bit");

                    b.Property<int>("TipoDespesa")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Despesa");
                });

            modelBuilder.Entity("Entities.Models.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(44)
                        .IsUnicode(false)
                        .HasColumnType("varchar(44)");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DataEmissao")
                        .HasColumnType("datetime");

                    b.Property<Guid>("DestinatarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmitenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("NumeroCliente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("RemetenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.Property<string>("XPed")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("xPed");

                    b.HasKey("Id");

                    b.HasIndex("DestinatarioId");

                    b.HasIndex("RemetenteId");

                    b.HasIndex("TipoDocumentoId");

                    b.HasIndex(new[] { "Chave" }, "UC_DocumentoChave")
                        .IsUnique();

                    b.HasIndex(new[] { "EmitenteId", "TipoDocumentoId", "Numero", "Serie", "NumeroCliente" }, "UC_Documento_IdEmitente_IdTipoDocumento_Numero_Serie_NumeroCliente")
                        .IsUnique();

                    b.ToTable("Documento", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Documento1", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Ativo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("datetime");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_Documento_Id");

                    b.HasIndex("DocumentoId");

                    b.HasIndex("TenantId");

                    b.ToTable("Documento", "tnt");
                });

            modelBuilder.Entity("Entities.Models.DocumentoFilialGrupo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EnderecoServicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("FilialAtualId")
                        .HasColumnType("int");

                    b.Property<int?>("FilialDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("FilialId")
                        .HasColumnType("int");

                    b.Property<Guid?>("FilialLastMileGrupoItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TransportadorLastMileGrupoItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoServicoId");

                    b.ToTable("DocumentoFilialGrupo", "tnt");
                });

            modelBuilder.Entity("Entities.Models.DocumentoImposto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CEnq")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("cEnq");

                    b.Property<string>("CofinsCst")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<decimal?>("CofinspCofins")
                        .HasColumnType("numeric(18, 2)")
                        .HasColumnName("CofinspCOFINS");

                    b.Property<decimal?>("CofinsvBc")
                        .HasColumnType("numeric(18, 2)")
                        .HasColumnName("CofinsvBC");

                    b.Property<decimal?>("CofinsvCofins")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<string>("Icms")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IcmsCst")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("IpiCst")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<int?>("ModBc")
                        .HasColumnType("int");

                    b.Property<string>("Orig")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<decimal?>("PIcms")
                        .HasColumnType("numeric(18, 2)")
                        .HasColumnName("pIcms");

                    b.Property<string>("PisCst")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<decimal?>("PispPis")
                        .HasColumnType("numeric(18, 2)")
                        .HasColumnName("PispPIS");

                    b.Property<decimal?>("PisvBc")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<decimal?>("PisvPis")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<decimal?>("VBc")
                        .HasColumnType("numeric(18, 2)")
                        .HasColumnName("vBC");

                    b.Property<decimal?>("VIcms")
                        .HasColumnType("numeric(18, 2)")
                        .HasColumnName("vIcms");

                    b.HasKey("Id")
                        .HasName("PK_DocumentoPadraoImposto");

                    b.ToTable("DocumentoImposto", (string)null);
                });

            modelBuilder.Entity("Entities.Models.DocumentoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CEan")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cEan");

                    b.Property<string>("CEantrib")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cEANTrib");

                    b.Property<string>("CProd")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cProd");

                    b.Property<string>("Cfop")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.Property<Guid>("DocumentoPadraoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("NItem")
                        .HasColumnType("int")
                        .HasColumnName("nItem");

                    b.Property<string>("Ncm")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("QCom")
                        .HasColumnType("int")
                        .HasColumnName("qCom");

                    b.Property<decimal?>("QTrib")
                        .HasColumnType("numeric(18, 2)")
                        .HasColumnName("qTrib");

                    b.Property<decimal?>("Quantidade")
                        .HasColumnType("numeric(18, 3)");

                    b.Property<int?>("UCom")
                        .HasColumnType("int")
                        .HasColumnName("uCom");

                    b.Property<string>("UTrib")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("uTrib");

                    b.Property<decimal?>("VProd")
                        .HasColumnType("numeric(18, 2)")
                        .HasColumnName("vProd");

                    b.Property<decimal?>("VUnCom")
                        .HasColumnType("numeric(18, 5)")
                        .HasColumnName("vUnCom");

                    b.Property<decimal?>("VUnTrib")
                        .HasColumnType("numeric(18, 5)")
                        .HasColumnName("vUnTrib");

                    b.Property<string>("XPed")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("xPed");

                    b.HasKey("Id")
                        .HasName("PK_DocumentoPadraoItem");

                    b.HasIndex("DocumentoPadraoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("DocumentoItem", (string)null);
                });

            modelBuilder.Entity("Entities.Models.DocumentoTotal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("MetragemCubica")
                        .HasColumnType("numeric(10, 3)");

                    b.Property<decimal?>("PesoBruto")
                        .HasColumnType("numeric(10, 3)");

                    b.Property<decimal?>("PesoCubado")
                        .HasColumnType("numeric(10, 3)");

                    b.Property<decimal?>("PesoLiquido")
                        .HasColumnType("numeric(10, 3)");

                    b.Property<decimal?>("ValorDaNota")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<decimal?>("Volumes")
                        .HasColumnType("numeric(10, 0)");

                    b.HasKey("Id")
                        .HasName("PK_DocumentoPadraoTotal");

                    b.ToTable("DocumentoTotal", (string)null);
                });

            modelBuilder.Entity("Entities.Models.DocumentoTransportador", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("InscricaoEstadual")
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)");

                    b.Property<string>("Municipio")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Nome")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id")
                        .HasName("PK_DocumentoPadraoTransportador");

                    b.ToTable("DocumentoTransportador", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Empresa", "tnt");
                });

            modelBuilder.Entity("Entities.Models.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BairroId")
                        .HasColumnType("int");

                    b.Property<string>("Cep")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("CodigoIbge")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("CodigoIBGE");

                    b.Property<string>("Complemento")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<int?>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<string>("NomeBairro")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("NomeMunicipio")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TipoEndereco")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.ToTable("Endereco", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Estado", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CepFinal")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("CepInicial")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<int>("IdPais")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("IdPais");

                    b.ToTable("Estado", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Filial", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool?>("Ativo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int?>("FilialPaiId")
                        .HasColumnType("int");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("FilialPaiId");

                    b.ToTable("Filial", "tnt");
                });

            modelBuilder.Entity("Entities.Models.FilialLastMile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BairroId")
                        .HasColumnType("int");

                    b.Property<string>("CepFinal")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("CepInicial")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<DateTime?>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("EstadoId")
                        .HasColumnType("int");

                    b.Property<int>("FilialId")
                        .HasColumnType("int");

                    b.Property<int?>("MunicipioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BairroId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("FilialId");

                    b.HasIndex("MunicipioId");

                    b.ToTable("FilialLastMile", "tnt");
                });

            modelBuilder.Entity("Entities.Models.FilialLastMileGrupo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<int?>("Ordem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FilialLastMileGrupo", "tnt");
                });

            modelBuilder.Entity("Entities.Models.FilialLastMileGrupoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FilialLastMileGrupoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FilialLastMileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FilialLastMileGrupoId");

                    b.HasIndex("FilialLastMileId");

                    b.ToTable("FilialLastMileGrupoItem", "tnt");
                });

            modelBuilder.Entity("Entities.Models.Municipio", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Cep")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<int?>("CodigoIbge")
                        .HasColumnType("int")
                        .HasColumnName("CodigoIBGE");

                    b.Property<int?>("MunicipioPaiId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("MunicipioPaiId");

                    b.ToTable("Municipio", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Pais", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Sigla")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.HasKey("Id");

                    b.ToTable("Pais");
                });

            modelBuilder.Entity("Entities.Models.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Fantasia")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Pessoa", (string)null);
                });

            modelBuilder.Entity("Entities.Models.PessoaEndereco", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EnderecoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId");

                    b.HasIndex("PessoaId");

                    b.ToTable("PessoaEndereco", (string)null);
                });

            modelBuilder.Entity("Entities.Models.PessoaFisica", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)");

                    b.Property<string>("Rg")
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Cpf" }, "UC_PessoaFisicaCpf")
                        .IsUnique();

                    b.ToTable("PessoaFisica", (string)null);
                });

            modelBuilder.Entity("Entities.Models.PessoaJuridica", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)");

                    b.Property<string>("InscricaoEstadual")
                        .IsRequired()
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)");

                    b.Property<string>("InscricaoMunicipal")
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Cnpj" }, "UC_PessoaJuridicaCnpj")
                        .IsUnique();

                    b.ToTable("PessoaJuridica", (string)null);
                });

            modelBuilder.Entity("Entities.Models.PessoaOutro", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Codigo" }, "UC_PessoaOutrosCodigo")
                        .IsUnique();

                    b.ToTable("PessoaOutros");
                });

            modelBuilder.Entity("Entities.Models.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PessoaId", "Codigo" }, "UC_ProdutoIdPessoaCodigo")
                        .IsUnique();

                    b.ToTable("Produto", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Romaneio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Romaneio", "tnt");
                });

            modelBuilder.Entity("Entities.Models.RomaneioCarga", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("DitanciaKm")
                        .HasColumnType("numeric(18, 3)");

                    b.Property<decimal?>("MetragemCubica")
                        .HasColumnType("numeric(18, 3)");

                    b.Property<int?>("Paradas")
                        .HasColumnType("int");

                    b.Property<decimal?>("PesoBruto")
                        .HasColumnType("numeric(18, 3)");

                    b.Property<Guid?>("VeiculoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("VeiculoTipoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VeiculoId");

                    b.HasIndex("VeiculoTipoId");

                    b.ToTable("RomaneioCarga", "tnt");
                });

            modelBuilder.Entity("Entities.Models.RomaneioDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RomaneioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RomaneioId", "DocumentoId" }, "UC_RomaneioDocumento_IdRomaneioIdDocumento")
                        .IsUnique();

                    b.ToTable("RomaneioDocumento", "tnt");
                });

            modelBuilder.Entity("Entities.Models.SistemaFinanceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<int>("AnoCopia")
                        .HasColumnType("int");

                    b.Property<int>("DiaFechamento")
                        .HasColumnType("int");

                    b.Property<bool>("GerarCopiaDespesa")
                        .HasColumnType("bit");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<int>("MesCopia")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SistemaFinanceiro");
                });

            modelBuilder.Entity("Entities.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Ativo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Tenant", (string)null);
                });

            modelBuilder.Entity("Entities.Models.TipoContum", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("TipoConta");
                });

            modelBuilder.Entity("Entities.Models.TipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TipoDocumento", (string)null);
                });

            modelBuilder.Entity("Entities.Models.TipoRntrc", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("TipoRntrc", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Transportador", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<string>("Rntrc")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("RntrcValidade")
                        .HasColumnType("date");

                    b.Property<int>("TipoRntrcId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoRntrcId");

                    b.ToTable("Transportador", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Transportador1", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Agencia")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("AgencidaDigito")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Banco")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("ChavePix")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CnpjCpfFavorecido")
                        .HasMaxLength(18)
                        .IsUnicode(false)
                        .HasColumnType("varchar(18)");

                    b.Property<string>("Conta")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ContaDigito")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("NomeFavorecido")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TipoContaId")
                        .HasColumnType("int");

                    b.Property<Guid>("TitularId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TransportadorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_Transportador_1");

                    b.HasIndex("TenantId");

                    b.HasIndex("TipoContaId");

                    b.HasIndex("TransportadorId");

                    b.ToTable("Transportador", "tnt");
                });

            modelBuilder.Entity("Entities.Models.TransportadorLastMile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BairroId")
                        .HasColumnType("int");

                    b.Property<string>("CepFinal")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("CepInicial")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<DateTime?>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("EstadoId")
                        .HasColumnType("int");

                    b.Property<int?>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<int>("TransportadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("TransportadorLastMile", "tnt");
                });

            modelBuilder.Entity("Entities.Models.TransportadorLastMileGrupo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<int?>("Ordem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TransportadorLastMileGrupo", "tnt");
                });

            modelBuilder.Entity("Entities.Models.TransportadorLastMileGrupoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TransportadorLastMileGrupoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TransportadorLastMileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TransportadorLastMileGrupoId");

                    b.HasIndex("TransportadorLastMileId");

                    b.ToTable("TransportadorLastMileGrupoItem", "tnt");
                });

            modelBuilder.Entity("Entities.Models.UsuarioSistemaFinanceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Administrador")
                        .HasColumnType("bit");

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdSistema")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<bool>("SistemaAtual")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdSistema");

                    b.ToTable("UsuarioSistemaFinanceiro");
                });

            modelBuilder.Entity("Entities.Models.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Ano")
                        .HasColumnType("int");

                    b.Property<decimal?>("CapacidadeM3")
                        .HasColumnType("numeric(10, 0)");

                    b.Property<decimal?>("CapacidadePeso")
                        .HasColumnType("numeric(10, 0)");

                    b.Property<string>("Chassi")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Combustivel")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Cor")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("Eixos")
                        .HasColumnType("int");

                    b.Property<string>("MarcaModelo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NumeroCrv")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<Guid?>("ProprietarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Renavan")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("VieculoTipoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProprietarioId");

                    b.HasIndex("VieculoTipoId");

                    b.HasIndex(new[] { "Placa" }, "UC_VeiculoPlaca")
                        .IsUnique();

                    b.ToTable("Veiculo", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Veiculo1", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VeiculoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_Veiculo_1");

                    b.HasIndex("TenantId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Veiculo", "tnt");
                });

            modelBuilder.Entity("Entities.Models.VeiculoTipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("VeiculoTipo", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Bairro", b =>
                {
                    b.HasOne("Entities.Models.Municipio", "Municipio")
                        .WithMany("Bairros")
                        .HasForeignKey("MunicipioId")
                        .IsRequired()
                        .HasConstraintName("FK_Bairro_MunicipioId_Municipio");

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("Entities.Models.Documento", b =>
                {
                    b.HasOne("Entities.Models.Pessoa", "Destinatario")
                        .WithMany("DocumentoDestinatarios")
                        .HasForeignKey("DestinatarioId")
                        .IsRequired()
                        .HasConstraintName("FK_Documento_DestinatarioId_Pessoa");

                    b.HasOne("Entities.Models.Pessoa", "Emitente")
                        .WithMany("DocumentoEmitentes")
                        .HasForeignKey("EmitenteId")
                        .IsRequired()
                        .HasConstraintName("FK_Documento_EmitenteId_Pessoa");

                    b.HasOne("Entities.Models.Pessoa", "Remetente")
                        .WithMany("DocumentoRemetentes")
                        .HasForeignKey("RemetenteId")
                        .IsRequired()
                        .HasConstraintName("FK_Documento_RemetenteId_Pessoa");

                    b.HasOne("Entities.Models.TipoDocumento", "TipoDocumento")
                        .WithMany("Documentos")
                        .HasForeignKey("TipoDocumentoId")
                        .IsRequired()
                        .HasConstraintName("FK_Documento_IdTipoDocumento_TipoDocumento");

                    b.Navigation("Destinatario");

                    b.Navigation("Emitente");

                    b.Navigation("Remetente");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("Entities.Models.Documento1", b =>
                {
                    b.HasOne("Entities.Models.Documento", "Documento")
                        .WithMany("Documento1s")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Documento_DocumentoId_Documento");

                    b.HasOne("Entities.Models.Tenant", "Tenant")
                        .WithMany("Documento1s")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Documento_TenantId_Tenant");

                    b.Navigation("Documento");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Entities.Models.DocumentoFilialGrupo", b =>
                {
                    b.HasOne("Entities.Models.Endereco", "EnderecoServico")
                        .WithMany("DocumentoFilialGrupos")
                        .HasForeignKey("EnderecoServicoId")
                        .IsRequired()
                        .HasConstraintName("FK_DocumentoRegiao_IdEnderecoServicoId_Endereco");

                    b.HasOne("Entities.Models.Documento1", "IdNavigation")
                        .WithOne("DocumentoFilialGrupo")
                        .HasForeignKey("Entities.Models.DocumentoFilialGrupo", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DocumentoRegiao_Id_Documento");

                    b.Navigation("EnderecoServico");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("Entities.Models.DocumentoImposto", b =>
                {
                    b.HasOne("Entities.Models.Documento", "IdNavigation")
                        .WithOne("DocumentoImposto")
                        .HasForeignKey("Entities.Models.DocumentoImposto", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DocumentoImposto_Id_Documento");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("Entities.Models.DocumentoItem", b =>
                {
                    b.HasOne("Entities.Models.Documento", "DocumentoPadrao")
                        .WithMany("DocumentoItems")
                        .HasForeignKey("DocumentoPadraoId")
                        .IsRequired()
                        .HasConstraintName("FK_DocumentoItem_DocumentoPadraoId_Documento");

                    b.HasOne("Entities.Models.Produto", "Produto")
                        .WithMany("DocumentoItems")
                        .HasForeignKey("ProdutoId")
                        .IsRequired()
                        .HasConstraintName("FK_DocumentoPadraoItem_ProdutoId_Produto");

                    b.Navigation("DocumentoPadrao");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Entities.Models.DocumentoTotal", b =>
                {
                    b.HasOne("Entities.Models.Documento", "IdNavigation")
                        .WithOne("DocumentoTotal")
                        .HasForeignKey("Entities.Models.DocumentoTotal", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DocumentoTotal_Id_Documento");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("Entities.Models.DocumentoTransportador", b =>
                {
                    b.HasOne("Entities.Models.Documento", "IdNavigation")
                        .WithOne("DocumentoTransportador")
                        .HasForeignKey("Entities.Models.DocumentoTransportador", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DocumentoPadraoTransportador_Id_Documento");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("Entities.Models.Empresa", b =>
                {
                    b.HasOne("Entities.Models.Tenant", "Tenant")
                        .WithMany("Empresas")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Empresa_TenantId_Tenant");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Entities.Models.Estado", b =>
                {
                    b.HasOne("Entities.Models.Pais", "IdPaisNavigation")
                        .WithMany("Estados")
                        .HasForeignKey("IdPais")
                        .IsRequired()
                        .HasConstraintName("FK_Estado_IdPais_Pais");

                    b.Navigation("IdPaisNavigation");
                });

            modelBuilder.Entity("Entities.Models.Filial", b =>
                {
                    b.HasOne("Entities.Models.Empresa", "Empresa")
                        .WithMany("Filials")
                        .HasForeignKey("EmpresaId")
                        .IsRequired()
                        .HasConstraintName("FK_Filial_EmpresaId_Empresa");

                    b.HasOne("Entities.Models.Filial", "FilialPai")
                        .WithMany("InverseFilialPai")
                        .HasForeignKey("FilialPaiId")
                        .HasConstraintName("FK_Filial_FilialPaiId_Filial");

                    b.Navigation("Empresa");

                    b.Navigation("FilialPai");
                });

            modelBuilder.Entity("Entities.Models.FilialLastMile", b =>
                {
                    b.HasOne("Entities.Models.Bairro", "Bairro")
                        .WithMany("FilialLastMiles")
                        .HasForeignKey("BairroId")
                        .HasConstraintName("FK_FilialRegiao_BairroId_Bairro");

                    b.HasOne("Entities.Models.Estado", "Estado")
                        .WithMany("FilialLastMiles")
                        .HasForeignKey("EstadoId")
                        .HasConstraintName("FK_FilialLastMile_EstadoId_Estado");

                    b.HasOne("Entities.Models.Filial", "Filial")
                        .WithMany("FilialLastMiles")
                        .HasForeignKey("FilialId")
                        .IsRequired()
                        .HasConstraintName("FK_FilialLastMile_FilialId_Filial");

                    b.HasOne("Entities.Models.Municipio", "Municipio")
                        .WithMany("FilialLastMiles")
                        .HasForeignKey("MunicipioId")
                        .HasConstraintName("FK_FilialLastMile_MunicipioId_Municipio");

                    b.Navigation("Bairro");

                    b.Navigation("Estado");

                    b.Navigation("Filial");

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("Entities.Models.FilialLastMileGrupoItem", b =>
                {
                    b.HasOne("Entities.Models.FilialLastMileGrupo", "FilialLastMileGrupo")
                        .WithMany("FilialLastMileGrupoItems")
                        .HasForeignKey("FilialLastMileGrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FilialLastMileGrupoItem_FilialLastMileGrupoItem_FilialLastMileGrupo");

                    b.HasOne("Entities.Models.FilialLastMile", "FilialLastMile")
                        .WithMany("FilialLastMileGrupoItems")
                        .HasForeignKey("FilialLastMileId")
                        .IsRequired()
                        .HasConstraintName("FK_FilialLastMileGrupoItem_FilialLastMileId_FilialLastMile");

                    b.Navigation("FilialLastMile");

                    b.Navigation("FilialLastMileGrupo");
                });

            modelBuilder.Entity("Entities.Models.Municipio", b =>
                {
                    b.HasOne("Entities.Models.Municipio", "MunicipioPai")
                        .WithMany("InverseMunicipioPai")
                        .HasForeignKey("MunicipioPaiId")
                        .HasConstraintName("FK_Municipio_MunicipioPaiId_Municipio");

                    b.Navigation("MunicipioPai");
                });

            modelBuilder.Entity("Entities.Models.PessoaEndereco", b =>
                {
                    b.HasOne("Entities.Models.Endereco", "Endereco")
                        .WithMany("PessoaEnderecos")
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PessoaEndereco_EnderecoId_Endereco");

                    b.HasOne("Entities.Models.Pessoa", "Pessoa")
                        .WithMany("PessoaEnderecos")
                        .HasForeignKey("PessoaId")
                        .IsRequired()
                        .HasConstraintName("FK_PessoaEndereco_PessoaId_Pessoa");

                    b.Navigation("Endereco");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Entities.Models.PessoaFisica", b =>
                {
                    b.HasOne("Entities.Models.Pessoa", "IdNavigation")
                        .WithOne("PessoaFisica")
                        .HasForeignKey("Entities.Models.PessoaFisica", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PessoaFisica_Id_Pessoa");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("Entities.Models.PessoaJuridica", b =>
                {
                    b.HasOne("Entities.Models.Pessoa", "IdNavigation")
                        .WithOne("PessoaJuridica")
                        .HasForeignKey("Entities.Models.PessoaJuridica", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PessoaJuridica_Id_Pessoa");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("Entities.Models.PessoaOutro", b =>
                {
                    b.HasOne("Entities.Models.Pessoa", "IdNavigation")
                        .WithOne("PessoaOutro")
                        .HasForeignKey("Entities.Models.PessoaOutro", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PessoaOutros_Id_Pessoa");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("Entities.Models.Produto", b =>
                {
                    b.HasOne("Entities.Models.Pessoa", "Pessoa")
                        .WithMany("Produtos")
                        .HasForeignKey("PessoaId")
                        .IsRequired()
                        .HasConstraintName("FK_Produto_PessoaId_Pessoa");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Entities.Models.Romaneio", b =>
                {
                    b.HasOne("Entities.Models.Tenant", "Tenant")
                        .WithMany("Romaneios")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Romaneio_TenantId_Tenant");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Entities.Models.RomaneioCarga", b =>
                {
                    b.HasOne("Entities.Models.Romaneio", "IdNavigation")
                        .WithOne("RomaneioCarga")
                        .HasForeignKey("Entities.Models.RomaneioCarga", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RomaneioCarga_Id_Romaneio");

                    b.HasOne("Entities.Models.Veiculo1", "Veiculo")
                        .WithMany("RomaneioCargas")
                        .HasForeignKey("VeiculoId")
                        .HasConstraintName("FK_RomaneioCarga_VeiculoId_Veiculo");

                    b.HasOne("Entities.Models.VeiculoTipo", "VeiculoTipo")
                        .WithMany("RomaneioCargas")
                        .HasForeignKey("VeiculoTipoId")
                        .HasConstraintName("FK_RomaneioCarga_VeiculoTipoId_VeiculoTipo");

                    b.Navigation("IdNavigation");

                    b.Navigation("Veiculo");

                    b.Navigation("VeiculoTipo");
                });

            modelBuilder.Entity("Entities.Models.RomaneioDocumento", b =>
                {
                    b.HasOne("Entities.Models.Documento1", "IdNavigation")
                        .WithOne("RomaneioDocumento")
                        .HasForeignKey("Entities.Models.RomaneioDocumento", "Id")
                        .IsRequired()
                        .HasConstraintName("FK_RomaneioDocumento_Id_Documento");

                    b.HasOne("Entities.Models.Romaneio", "Romaneio")
                        .WithMany("RomaneioDocumentos")
                        .HasForeignKey("RomaneioId")
                        .IsRequired()
                        .HasConstraintName("FK_RomaneioDocumento_Id_Romaneio");

                    b.Navigation("IdNavigation");

                    b.Navigation("Romaneio");
                });

            modelBuilder.Entity("Entities.Models.Transportador", b =>
                {
                    b.HasOne("Entities.Models.Pessoa", "IdNavigation")
                        .WithOne("Transportador")
                        .HasForeignKey("Entities.Models.Transportador", "Id")
                        .IsRequired()
                        .HasConstraintName("FK_Transportador_Id_Pessoa");

                    b.HasOne("Entities.Models.TipoRntrc", "TipoRntrc")
                        .WithMany("Transportadors")
                        .HasForeignKey("TipoRntrcId")
                        .IsRequired()
                        .HasConstraintName("FK_Transportador_TipoRntrcId_TipoRntrc");

                    b.Navigation("IdNavigation");

                    b.Navigation("TipoRntrc");
                });

            modelBuilder.Entity("Entities.Models.Transportador1", b =>
                {
                    b.HasOne("Entities.Models.Pessoa", "IdNavigation")
                        .WithOne("Transportador1")
                        .HasForeignKey("Entities.Models.Transportador1", "Id")
                        .IsRequired()
                        .HasConstraintName("FK_Transportador_TitularId_Pessoa");

                    b.HasOne("Entities.Models.Tenant", "Tenant")
                        .WithMany("Transportador1s")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Transportador_TenantId_Tenant");

                    b.HasOne("Entities.Models.TipoContum", "TipoConta")
                        .WithMany("Transportador1s")
                        .HasForeignKey("TipoContaId")
                        .HasConstraintName("FK_Transportador_TipoContaId_TipoConta");

                    b.HasOne("Entities.Models.Transportador", "Transportador")
                        .WithMany("Transportador1s")
                        .HasForeignKey("TransportadorId")
                        .IsRequired()
                        .HasConstraintName("FK_Transportador_TransportadorId_Transportador");

                    b.Navigation("IdNavigation");

                    b.Navigation("Tenant");

                    b.Navigation("TipoConta");

                    b.Navigation("Transportador");
                });

            modelBuilder.Entity("Entities.Models.TransportadorLastMile", b =>
                {
                    b.HasOne("Entities.Models.Estado", "Estado")
                        .WithMany("TransportadorLastMiles")
                        .HasForeignKey("EstadoId")
                        .HasConstraintName("FK_TransportadorLastMile_EstadoId_Estado");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("Entities.Models.TransportadorLastMileGrupoItem", b =>
                {
                    b.HasOne("Entities.Models.TransportadorLastMileGrupo", "TransportadorLastMileGrupo")
                        .WithMany("TransportadorLastMileGrupoItems")
                        .HasForeignKey("TransportadorLastMileGrupoId")
                        .IsRequired()
                        .HasConstraintName("FK_TransportadorLastMileGrupoItem_TransportadorLastMileGrupoItem_TransportadorLastMileGrupo");

                    b.HasOne("Entities.Models.TransportadorLastMile", "TransportadorLastMile")
                        .WithMany("TransportadorLastMileGrupoItems")
                        .HasForeignKey("TransportadorLastMileId")
                        .IsRequired()
                        .HasConstraintName("FK_TransportadorLastMileGrupoItem_TransportadorLastMileId_TransportadorLastMile");

                    b.Navigation("TransportadorLastMile");

                    b.Navigation("TransportadorLastMileGrupo");
                });

            modelBuilder.Entity("Entities.Models.UsuarioSistemaFinanceiro", b =>
                {
                    b.HasOne("Entities.Models.SistemaFinanceiro", "SistemaFinanceiro")
                        .WithMany()
                        .HasForeignKey("IdSistema")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SistemaFinanceiro");
                });

            modelBuilder.Entity("Entities.Models.Veiculo", b =>
                {
                    b.HasOne("Entities.Models.Pessoa", "Proprietario")
                        .WithMany("Veiculos")
                        .HasForeignKey("ProprietarioId")
                        .HasConstraintName("FK_Veiculo_ProprietarioId_Pessoa");

                    b.HasOne("Entities.Models.VeiculoTipo", "VieculoTipo")
                        .WithMany("Veiculos")
                        .HasForeignKey("VieculoTipoId")
                        .HasConstraintName("FK_Veiculo_VeiculoTipoId_VeiculoTipo");

                    b.Navigation("Proprietario");

                    b.Navigation("VieculoTipo");
                });

            modelBuilder.Entity("Entities.Models.Veiculo1", b =>
                {
                    b.HasOne("Entities.Models.Tenant", "Tenant")
                        .WithMany("Veiculo1s")
                        .HasForeignKey("TenantId")
                        .HasConstraintName("FK_Veiculo_TenantId_Tenant");

                    b.HasOne("Entities.Models.Veiculo", "Veiculo")
                        .WithMany("Veiculo1s")
                        .HasForeignKey("VeiculoId")
                        .HasConstraintName("FK_Veiculo_VeiculoId_Veiculo");

                    b.Navigation("Tenant");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Entities.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Entities.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Entities.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Bairro", b =>
                {
                    b.Navigation("FilialLastMiles");
                });

            modelBuilder.Entity("Entities.Models.Documento", b =>
                {
                    b.Navigation("Documento1s");

                    b.Navigation("DocumentoImposto");

                    b.Navigation("DocumentoItems");

                    b.Navigation("DocumentoTotal");

                    b.Navigation("DocumentoTransportador");
                });

            modelBuilder.Entity("Entities.Models.Documento1", b =>
                {
                    b.Navigation("DocumentoFilialGrupo");

                    b.Navigation("RomaneioDocumento");
                });

            modelBuilder.Entity("Entities.Models.Empresa", b =>
                {
                    b.Navigation("Filials");
                });

            modelBuilder.Entity("Entities.Models.Endereco", b =>
                {
                    b.Navigation("DocumentoFilialGrupos");

                    b.Navigation("PessoaEnderecos");
                });

            modelBuilder.Entity("Entities.Models.Estado", b =>
                {
                    b.Navigation("FilialLastMiles");

                    b.Navigation("TransportadorLastMiles");
                });

            modelBuilder.Entity("Entities.Models.Filial", b =>
                {
                    b.Navigation("FilialLastMiles");

                    b.Navigation("InverseFilialPai");
                });

            modelBuilder.Entity("Entities.Models.FilialLastMile", b =>
                {
                    b.Navigation("FilialLastMileGrupoItems");
                });

            modelBuilder.Entity("Entities.Models.FilialLastMileGrupo", b =>
                {
                    b.Navigation("FilialLastMileGrupoItems");
                });

            modelBuilder.Entity("Entities.Models.Municipio", b =>
                {
                    b.Navigation("Bairros");

                    b.Navigation("FilialLastMiles");

                    b.Navigation("InverseMunicipioPai");
                });

            modelBuilder.Entity("Entities.Models.Pais", b =>
                {
                    b.Navigation("Estados");
                });

            modelBuilder.Entity("Entities.Models.Pessoa", b =>
                {
                    b.Navigation("DocumentoDestinatarios");

                    b.Navigation("DocumentoEmitentes");

                    b.Navigation("DocumentoRemetentes");

                    b.Navigation("PessoaEnderecos");

                    b.Navigation("PessoaFisica");

                    b.Navigation("PessoaJuridica");

                    b.Navigation("PessoaOutro");

                    b.Navigation("Produtos");

                    b.Navigation("Transportador");

                    b.Navigation("Transportador1");

                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("Entities.Models.Produto", b =>
                {
                    b.Navigation("DocumentoItems");
                });

            modelBuilder.Entity("Entities.Models.Romaneio", b =>
                {
                    b.Navigation("RomaneioCarga");

                    b.Navigation("RomaneioDocumentos");
                });

            modelBuilder.Entity("Entities.Models.Tenant", b =>
                {
                    b.Navigation("Documento1s");

                    b.Navigation("Empresas");

                    b.Navigation("Romaneios");

                    b.Navigation("Transportador1s");

                    b.Navigation("Veiculo1s");
                });

            modelBuilder.Entity("Entities.Models.TipoContum", b =>
                {
                    b.Navigation("Transportador1s");
                });

            modelBuilder.Entity("Entities.Models.TipoDocumento", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("Entities.Models.TipoRntrc", b =>
                {
                    b.Navigation("Transportadors");
                });

            modelBuilder.Entity("Entities.Models.Transportador", b =>
                {
                    b.Navigation("Transportador1s");
                });

            modelBuilder.Entity("Entities.Models.TransportadorLastMile", b =>
                {
                    b.Navigation("TransportadorLastMileGrupoItems");
                });

            modelBuilder.Entity("Entities.Models.TransportadorLastMileGrupo", b =>
                {
                    b.Navigation("TransportadorLastMileGrupoItems");
                });

            modelBuilder.Entity("Entities.Models.Veiculo", b =>
                {
                    b.Navigation("Veiculo1s");
                });

            modelBuilder.Entity("Entities.Models.Veiculo1", b =>
                {
                    b.Navigation("RomaneioCargas");
                });

            modelBuilder.Entity("Entities.Models.VeiculoTipo", b =>
                {
                    b.Navigation("RomaneioCargas");

                    b.Navigation("Veiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
